// Single source of truth for the projects grid.
//
// Adding a project means adding one entry here — the card markup, the filter
// counts, the sort order and the inspect modal all read from this array. The
// cards were 301 lines of near-identical HTML in index.html before this.
//
// Every string is set with textContent or setAttribute when rendered, never
// innerHTML, so no value here needs HTML escaping.

export const projectsData = [
  {
    id: 'orrery',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'Orrery',
    overlayLabel: '3D SIMULATION',
    category: 'experiment',  year: 2026,
    thumb: 'assets/thumbnails/orerry-thumb.jpg',
    thumbAlt: 'Orrery project preview',  width: 1200, height: 606,
    tech: 'CSS Animations • Fallout Terminal • Web Audio API',
    metrics: '9 planets · Web Audio API · 60fps',
    desc: '3D orrery with Fallout 3-style terminal and typewriter sounds',
    descUa: '3D-орбітальна модель планет з терміналом у стилі Fallout 3 та звуками друкарської машинки',
    descEs: 'Órbita 3D con terminal estilo Fallout 3 y sonidos de máquina de escribir',
    devlog: 'Learned 3D CSS transforms and orbital mechanics with the vanilla Canvas API',
    summary: '3D orrery with Fallout 3 inspired terminal interactions and sound.',
    challenge: 'Making orbital paths and timing feel physically convincing using only CSS transforms and JS math, with no physics library.',
    url: 'https://orrery.laddtnov.xyz/',
    visitAria: 'Open Orrery project in a new tab',
    inspectAria: 'Inspect Orrery project',
    shareAria: 'Copy link to Orrery project',
  },
  {
    id: 'libra',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'Libra',
    overlayLabel: 'BOOK TRACKER',
    category: 'tool',  year: 2026,
    thumb: 'assets/thumbnails/libra-thumb.jpg',
    thumbAlt: 'Libra project preview',  width: 1200, height: 623,
    tech: 'Neon Design • Fallout Terminal • Progress Tracking',
    metrics: 'LocalStorage sync · Progress tracking',
    desc: 'Futuristic book tracking with terminal interface and sound effects',
    descUa: 'Футуристичний трекер книг з терміналом і звуковими ефектами',
    descEs: 'Seguimiento de libros futurista con interfaz de terminal y efectos de sonido',
    devlog: 'Learned localStorage CRUD patterns and how to build a terminal-style UI from scratch',
    summary: 'Book tracking app with terminal visuals, neon panels, and progress modules.',
    challenge: 'Designing a persistent localStorage data model for books and progress that survives edits, reorders, and refreshes without corruption.',
    url: 'https://libra.laddtnov.xyz/',
    visitAria: 'Open Libra project in a new tab',
    inspectAria: 'Inspect Libra project',
    shareAria: 'Copy link to Libra project',
  },
  {
    id: 'breach-os',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'Breach OS',
    overlayLabel: 'CARD GAME',
    category: 'game',  year: 2025,
    thumb: 'assets/thumbnails/breach-os-thumb.jpg',
    thumbAlt: 'Breach OS project preview',  width: 1200, height: 1066,
    tech: 'JavaScript • CSS Animations • LocalStorage • Mission System',
    metrics: '6 missions · 120+ card pairs',
    desc: 'Cyberpunk-themed memory card game with missions and neon effects',
    descUa: 'Кіберпанк гра на пам\'ять з картками, місіями та неоновими ефектами',
    descEs: 'Juego de memoria con temática cyberpunk, misiones y efectos de neón',
    devlog: 'Learned game loop logic and CSS card-flip animation sequencing',
    summary: 'Cyberpunk memory game with mission loops, animations, and arcade progression.',
    challenge: 'Building a card-flip game loop with mission progression and difficulty scaling that stays smooth in vanilla JS.',
    url: 'https://breachos.app/',
    visitAria: 'Open Breach OS project in a new tab',
    inspectAria: 'Inspect Breach OS project',
    shareAria: 'Copy link to Breach OS project',
  },
  {
    id: 'cogsworth',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'Cogsworth',
    overlayLabel: 'SUDOKU PWA',
    category: 'game tool',  year: 2025,
    thumb: 'assets/thumbnails/cogsworth-thumb.jpg',
    thumbAlt: 'Cogsworth project preview',  width: 960, height: 1200,
    tech: 'JavaScript • PWA • Steampunk Design',
    metrics: 'PWA installable · 5 rank tiers',
    desc: 'Steampunk-themed Sudoku with rank system, survival mode and nixie tube UI',
    descUa: 'Судоку у стилі стімпанк з системою рангів, режимом виживання та інтерфейсом на основі нікси-індикаторів',
    descEs: 'Sudoku con temática steampunk, sistema de rangos, modo supervivencia e interfaz de tubos nixie',
    devlog: 'Learned Sudoku constraint-solving algorithms and PWA Service Worker caching',
    summary: 'Steampunk sudoku with rank systems, survival mode, and PWA install support.',
    challenge: 'Writing a Sudoku puzzle generator and validator, then wiring up offline-first caching with a Service Worker for PWA install.',
    url: 'https://cogsworth.laddtnov.xyz/',
    visitAria: 'Open Cogsworth project in a new tab',
    inspectAria: 'Inspect Cogsworth project',
    shareAria: 'Copy link to Cogsworth project',
  },
  {
    id: 'timeflow',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'TimeFlow',
    overlayLabel: 'REACT APP',
    category: 'tool productivity',  year: 2026,  isNew: true,
    thumb: 'assets/thumbnails/timeflow-thumb.jpg',
    thumbAlt: 'TimeFlow project preview',  width: 1200, height: 581,
    tech: 'React • Vite • CSS Modules',
    metrics: 'Weekly view · Appointment scheduling · Event management',
    desc: 'React-powered appointment tracker with weekly calendar and neon cyberpunk UI',
    descUa: 'Трекер зустрічей на React з тижневим календарем та неоновим кіберпанк-інтерфейсом',
    descEs: 'Gestor de citas con React, calendario semanal e interfaz cyberpunk de neón',
    devlog: 'First React project — learned hooks, component state, and the Vite build tool',
    summary: 'React + Vite appointment tracker with weekly calendar view, event creation, and real-time scheduling.',
    challenge: 'First time using React and Vite — learning component state, hooks, and a build pipeline while building a working weekly calendar.',
    url: 'https://timeflow.laddtnov.xyz/',
    visitAria: 'Open TimeFlow project in a new tab',
    inspectAria: 'Inspect TimeFlow project',
    shareAria: 'Copy link to TimeFlow project',
  },
  {
    id: 'growflow',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'GrowFlow',
    overlayLabel: 'FINANCE TOOL',
    category: 'tool productivity',  year: 2026,  isNew: true,
    thumb: 'assets/thumbnails/growflow-thumb.jpg',
    thumbAlt: 'GrowFlow project preview',  width: 1200, height: 615,
    tech: 'Vanilla JS • Chart.js • LocalStorage',
    metrics: 'Income & expense logging · Balance tracking · Growth charts',
    desc: 'Personal finance tracker with neon dashboard and interactive Chart.js graphs',
    descUa: 'Особистий фінансовий трекер з неоновою панеллю та інтерактивними графіками Chart.js',
    descEs: 'Gestor de finanzas personales con panel de neón y gráficos interactivos con Chart.js',
    devlog: 'Learned Chart.js data visualization and financial calculation patterns',
    summary: 'Personal finance tracker with neon dashboard, income/expense logging, and interactive growth charts.',
    challenge: 'Wiring Chart.js to live-update from user-entered income and expense data while keeping running balance calculations accurate.',
    url: 'https://growflow.laddtnov.xyz/',
    visitAria: 'Open GrowFlow project in a new tab',
    inspectAria: 'Inspect GrowFlow project',
    shareAria: 'Copy link to GrowFlow project',
  },
  {
    id: 'vitrum',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'Vitrum',
    overlayLabel: 'CHESS GAME',
    category: 'game experiment',  year: 2024,
    thumb: 'assets/thumbnails/vitrum-thumb.jpg',
    thumbAlt: 'Vitrum project preview',  width: 1200, height: 592,
    tech: 'JavaScript • CSS Glassmorphism • Game Logic',
    metrics: 'Full chess rules · Touch support',
    desc: 'Elegant glass-themed chess game with smooth animations',
    descUa: 'Елегантні шахи у скляній тематиці з плавними анімаціями',
    descEs: 'Elegante juego de ajedrez con estilo cristal y animaciones suaves',
    devlog: 'Learned chess piece movement rules and CSS transition choreography',
    summary: 'Glassmorphism chess experience focused on elegant visuals and smooth piece motion.',
    challenge: 'Implementing full chess move legality, including special rules like castling and en passant, in vanilla JS with a glassmorphism UI.',
    url: 'https://vitrum.bynov.one/',
    visitAria: 'Open Vitrum project in a new tab',
    inspectAria: 'Inspect Vitrum project',
    shareAria: 'Copy link to Vitrum project',
  },
  {
    id: 'trailune',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'Trailune',
    overlayLabel: 'TRAVEL TRACKER',
    category: 'tool productivity',  year: 2026,
    thumb: 'assets/thumbnails/trailune-thumb.jpg',
    thumbAlt: 'Trailune project preview',  width: 1200, height: 615,
    tech: 'SvelteKit • TypeScript • LocalStorage',
    metrics: 'Trip journals · Packing checklists · World map of visited countries',
    desc: 'Local-only travel tracker with trip journals, packing checklists, and a world map of visited countries',
    descUa: 'Локальний трекер подорожей з журналами поїздок, чек-листами для пакування та картою відвіданих країн',
    descEs: 'Tracker de viajes local con diarios de viaje, listas de equipaje y mapa de países visitados',
    devlog: 'First SvelteKit + TypeScript build — learned reactive stores, file-based routing, and typed data models',
    summary: 'SvelteKit + TypeScript travel tracker — trip journals, packing checklists, and a world map of visited countries, all stored locally.',
    challenge: 'First time with SvelteKit and TypeScript — learning reactive stores, file-based routing, and typed localStorage data models while keeping the app fully local, no backend.',
    url: 'https://trailune.laddtnov.xyz/',
    visitAria: 'Open Trailune project in a new tab',
    inspectAria: 'Inspect Trailune project',
    shareAria: 'Copy link to Trailune project',
  },
  {
    id: 'voidarium',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'Voidarium',
    overlayLabel: 'GALAXY MAP',
    category: 'game experiment',  year: 2026,
    thumb: 'assets/thumbnails/voidarium-thumb.jpg',
    thumbAlt: 'Voidarium project preview',  width: 1200, height: 615,
    tech: 'Vanilla JS • Canvas API • Zero Dependencies',
    metrics: 'Click-to-travel navigation · Explorable galaxies · Black holes & supermassive stars',
    desc: 'Interactive animated galaxy map — a spinning canvas universe with click-to-travel navigation, black holes, and supermassive stars',
    descUa: 'Інтерактивна анімована карта галактик — космічний всесвіт на Canvas з навігацією кліком, чорними дірами та надмасивними зорями',
    descEs: 'Mapa de galaxias animado e interactivo — un universo en canvas con navegación al hacer clic, agujeros negros y estrellas supermasivas',
    devlog: 'Learned canvas pan/zoom math and how to fake convincing cosmic scale with zero dependencies',
    summary: 'Interactive animated galaxy map — a spinning canvas universe with click-to-travel navigation, explorable galaxy interiors, black holes, supermassive stars, and cosmic voids.',
    challenge: 'Rendering a convincing sense of cosmic scale and depth with only the vanilla Canvas API — panning, zooming, and click-to-travel across dozens of objects while keeping everything smooth with zero dependencies.',
    url: 'https://voidarium.vercel.app/',
    visitAria: 'Open Voidarium project in a new tab',
    inspectAria: 'Inspect Voidarium project',
    shareAria: 'Copy link to Voidarium project',
  },
  {
    id: 'cyberpunk-ui',
    visitLabel: 'Visit', visitUa: 'Демо', visitEs: 'Demo',
    title: 'cyberpunk-ui',
    overlayLabel: 'CSS LIBRARY',
    category: 'tool',  year: 2026,  isNew: true,
    thumb: 'assets/thumbnails/cyberpunk-ui-thumb.jpg',
    thumbAlt: 'cyberpunk-ui CSS kit preview',  width: 1200, height: 615,
    tech: 'Vanilla CSS • Design Tokens • Zero Dependencies',
    metrics: 'npm i @laddtnov/cyberpunk-ui · Neon tokens · Glow/glitch/scanline effects · WCAG light theme',
    desc: 'My first npm package — a cyberpunk CSS kit with neon tokens, glow/glitch/scanline effects, and components, zero dependencies',
    descUa: 'Мій перший npm-пакет — кіберпанк CSS-набір з неоновими токенами, ефектами glow/glitch/scanline та компонентами, без жодних залежностей',
    descEs: 'Mi primer paquete en npm — un kit CSS cyberpunk con tokens neón, efectos glow/glitch/scanline y componentes, sin dependencias',
    devlog: 'First published npm package — learned CSS namespacing, theme-aware token architecture, and the npm publish pipeline',
    summary: 'First npm package — a zero-dependency cyberpunk neon CSS kit: design tokens, glow/glitch/scanline effects, and holo components, extracted from this very portfolio and published as @laddtnov/cyberpunk-ui.',
    challenge: 'Turning battle-tested portfolio CSS into a real, published npm package — namespacing every class, making glows theme-aware with RGB-channel tokens, shipping a WCAG-safe light theme, and getting through the npm publish pipeline, all with no build step.',
    url: 'https://laddtnov.github.io/cyberpunk-ui/demo/',
    visitAria: 'Open cyberpunk-ui live demo in a new tab',
    inspectAria: 'Inspect cyberpunk-ui project',
    shareAria: 'Copy link to cyberpunk-ui project',
  },
  {
    id: 'neonflux',
    visitLabel: 'Visit', visitUa: 'Відвідати', visitEs: 'Visitar',
    title: 'Neonflux',
    overlayLabel: 'OBSIDIAN THEME',
    category: 'tool',  year: 2026,  isNew: true,
    thumb: 'assets/thumbnails/neonflux-thumb.jpg',
    thumbAlt: 'Neonflux Obsidian theme preview',  width: 1200, height: 615,
    tech: 'Vanilla CSS • Design Tokens • Zero JavaScript',
    metrics: 'In Obsidian\'s community catalog · WCAG-checked contrast · Latin + Cyrillic fonts embedded',
    desc: 'An Obsidian theme built on the cyberpunk-ui palette — neon on near-black, a real light mode, embedded Latin and Cyrillic fonts, zero JavaScript',
    descUa: 'Тема для Obsidian на палітрі cyberpunk-ui — неон на майже чорному, справжня світла тема, вбудовані шрифти для латиниці й кирилиці, нуль JavaScript',
    descEs: 'Un tema de Obsidian con la paleta de cyberpunk-ui — neón sobre casi negro, un modo claro real, fuentes latinas y cirílicas incrustadas, cero JavaScript',
    devlog: 'Learned that a poster palette and a reading palette are different problems — and that some bugs only appear inside the app',
    summary: 'An Obsidian theme sharing cyberpunk-ui\'s palette, accepted into Obsidian\'s community themes catalog. Neon on near-black with a light mode that holds up, six fonts embedded for Latin and Cyrillic, and zero JavaScript.',
    challenge: 'Making a poster palette survive being read for hours. Neon on black looks great in a screenshot and punishes you in a note, so accents were confined to headings, links and code tokens while prose stayed calm — and every colour was held to a stricter contrast floor than a normal web project, because muted text in a note app is still text.',
    url: 'https://community.obsidian.md/themes/neonflux',
    visitAria: 'Open Neonflux in the Obsidian theme catalog in a new tab',
    inspectAria: 'Inspect Neonflux project',
    shareAria: 'Copy link to Neonflux project',
  },
];
